/* Alimenta tabela CARGOS */

INSERT INTO cargos VALUES ( 'Presidente' );
INSERT INTO cargos VALUES ('Vp de Vendas');
INSERT INTO cargos VALUES ('Vp de Operacoes');
INSERT INTO cargos VALUES ('Vp Financeiro');
INSERT INTO cargos VALUES ('Vp de Administracao');
INSERT INTO cargos VALUES ('Gerente de Almoxarifado');
INSERT INTO cargos VALUES ('Representante de Vendas');
INSERT INTO cargos VALUES ('Stock Clerk');