/* Alimenta tabela CLIENTE*/

INSERT INTO cliente VALUES
 (201, 'Unisports', '55-2066101', '72 Via Bahia', 'Sao Paulo', NULL, 'Brazil', NULL, 'Excelente', 12, 2, 'Cliente solicita usualmente grandes pedidos');

INSERT INTO cliente VALUES
 (202, 'OJ Aheletics', '81-20101', '6741 Takashi Bolev', 'Osaka', NULL, 'Japan', NULL, 'Pobre', 14, 4, 'Cliente pode pagar somente em dinheiro');

INSERT INTO cliente VALUES
 (203, 'Delhi Sports', '91-10351', '4567 Chanakya', 'New Delhi', NULL, 'India', NULL, 'Bom', 12, 2, 'Cliente solicita usualmente grandes pedidos');

INSERT INTO cliente VALUES
 (204, 'Womansports', '1-33-2466101', '281 King Street', 'Washington', NULL, 'USA', NULL, 'Excelente', 11, 1, NULL);

INSERT INTO cliente VALUES
 (205, 'Kams Sporting Goods', '852-3564788', '15 Road', 'Hong Kong', NULL, NULL, NULL, 'Excelente', 15, 4, NULL);

INSERT INTO cliente VALUES
 (206, 'Sportique', '33-2257201', '172 Rua de Viole', 'Cannes', NULL, 'Franca', NULL, 'Excelente', 15, 5, 'Cliente espec. em futebol');

INSERT INTO cliente VALUES
 (207, 'Sweet Rock Sports', '234-6036201', '66 Santo Antonie', 'Lagos', NULL, 'Nigeria', NULL, 'Bom', NULL, 3, NULL);

INSERT INTO cliente VALUES
 (208, 'Muench Spots', '49-527454', '43 Gruenstrasse', 'Stuttgart', NULL, 'Alemanha', NULL, 'Bom', 15, 5, 'Cliente usualmente paga em cash');

INSERT INTO cliente VALUES
 (209, 'Beisbol Si!', '809-356777', '792 Praia Del Mar', 'Sao Pedro', NULL, 'Mexico', NULL, 'Excelente', 11, 1, NULL);

INSERT INTO cliente VALUES
 (210, 'Futbol Sonora', '52-4566101', '12 Via Saguaro', 'Nogales', NULL, 'Mexico', NULL, 'Excelente', 12, 2, 'Contato dificil por telefone');

INSERT INTO cliente VALUES
 (211, 'Kuhn''s Sports', '42-2466101', '7 Mondrony', 'Praga', NULL, 'Chekscolovaquia', NULL, 'Excelente', 12, 2, NULL);

INSERT INTO cliente VALUES
 (212, 'Hamada Sport', '20-1206101', '57A Corniche', 'Alexandria', NULL, 'Egito', NULL, 'Excelente', 13, 3, 'Cliente solicita usualmente grandes pedidos');

INSERT INTO cliente VALUES
 (213, 'Big John''s Sports', '1-320-1266101', '18th Street', 'Sao Francisco', 'CA', 'USA', '94117', 'Excelente', 11, 1, 'Cliente possui registro pendente');

INSERT INTO cliente VALUES
 (214, 'Ojibway Retail', '1-716-1244101', '415 Main Street', 'Buffalo', 'NY', 'USA', '14202', 'Pobre', 11, 1, NULL);

INSERT INTO cliente VALUES
 (215, 'Sporta Russia', '7-3806101', '600 Yekatamina', 'San Petersburg', NULL, 'Russia', NULL, 'Pobre', 15, 5, 'Cliente solicita usualmente pequenos pedidos');

/* Alimenta a tabela DEPT*/

INSERT INTO dept VALUES (10, 'Financeiro', 1);

INSERT INTO dept VALUES (31, 'Vendas', 1);

INSERT INTO dept VALUES (32, 'Vendas', 2);

INSERT INTO dept VALUES (33, 'Vendas', 3);

INSERT INTO dept VALUES (34, 'Vendas', 4);

INSERT INTO dept VALUES (35, 'Vendas', 5);

INSERT INTO dept VALUES (41, 'Operacoes', 1);

INSERT INTO dept VALUES (42, 'Operacoes', 2);

INSERT INTO dept VALUES (43, 'Operacoes', 3);

INSERT INTO dept VALUES (44, 'Operacoes', 4);

INSERT INTO dept VALUES (45, 'Operacoes', 5);

INSERT INTO dept VALUES (50, 'Administracao', 1);