/* Alimenta tabela EMP */

INSERT INTO emp VALUES (
 1, 'Velasquez', 'Carmen', 'cvelasqu',
 '03-MAR-90', NULL, NULL, 'Presidente', 50, 2500, NULL);

INSERT INTO emp VALUES (
 2, 'Ngao', 'LaDoris', 'lngao',
 '08-MAR-90', NULL, 1, 'Vp de Operacoes', 41, 1450, NULL);

INSERT INTO emp VALUES (
 3, 'Nagayama', 'Midori', 'mnagayam',
 '17-JUN-91', NULL, 1, 'Vp de Vendas', 31, 1400, NULL);

INSERT INTO emp VALUES (
 4, 'Quick-To-See', 'Mark', 'mquickto',
 '07-APR-90', NULL, 1, 'Vp Financeiro', 10, 1450, NULL);

INSERT INTO emp VALUES (
 5, 'Ropeburn', 'Audry', 'aropebur',
 '04-MAR-90', NULL, 1, 'Vp de Administracao', 50, 1550, NULL);

INSERT INTO emp VALUES (
 6, 'Urguhart', 'Molly', 'murguhar',
 '04-MAR-90', NULL, 2, 'Gerente de Almoxarifado', 41, 1200, NULL);

INSERT INTO emp VALUES (
 15, 'Dumas', 'Andre', 'adumas',
 '09-OCT-91', NULL, 3, 'Representante de Vendas', 35, 1450, 17);

INSERT INTO emp VALUES (
 7, 'Menchu', 'Roberta', 'rmenchu',
 '04-MAY-90', NULL, 2, 'Gerente de Almoxarifado', 42, 1250, NULL);

INSERT INTO emp VALUES (
 8, 'Biri', 'Ben', 'bbiri',
 '07-APR-90', NULL, 2, 'Gerente de Almoxarifado', 43, 1110, NULL);

INSERT INTO emp VALUES (
 9, 'Catchpole', 'Antoinette', 'acatchpo',
 '09-FEB-92', NULL, 2, 'Gerente de Almoxarifado', 44, 1300, NULL);

INSERT INTO emp VALUES (
 10, 'Havel', 'Marta', 'mhavel',
 '27-FEB-91', NULL, 2, 'Gerente de Almoxarifado', 45, 1307, NULL);

INSERT INTO emp VALUES (
 11, 'Magee', 'Colin', 'cmagee',
 '07-APR-90', NULL, 3, 'Representante de Vendas', 31, 1400, 10);

INSERT INTO emp VALUES (
 12, 'Giljum', 'Henry', 'hgiljum',
 '07-APR-92', NULL, 3, 'Representante de Vendas', 32, 1490, 12);

INSERT INTO emp VALUES (
 13, 'Sedeghi', 'Yasmin', 'ysedeghi',
 '07-APR-90', NULL, 3, 'Representante de Vendas', 33, 1515, 10);

INSERT INTO emp VALUES (
 14, 'Nguyen', 'Mai', 'mnguyen',
 '07-APR-90', NULL, 3, 'Representante de Vendas', 34, 1525, 15);


INSERT INTO emp VALUES (
 16, 'Maduro', 'Elena', 'emaduro',
 '09-OCT-91', NULL, 6, 'Stock Clerk', 41, 1400, NULL);

INSERT INTO emp VALUES (
 17, 'Smith', 'George', 'gsmith',
 '06-AUG-91', NULL, 6, 'Stock Clerk', 41, 1400, NULL);

INSERT INTO emp VALUES (
 18, 'Nozaki', 'Akira', 'anozaki',
 '09-FEB-91', NULL, 7, 'Stock Clerk', 42, 1200, NULL);

INSERT INTO emp VALUES (
 19, 'Patel', 'Vikram', 'vpatel',
 '09-OCT-91', NULL, 7, 'Stock Clerk', 42, 985, NULL);

INSERT INTO emp VALUES (
 20, 'Newman', 'Chad', 'cnewman',
 '09-OCT-91', NULL, 8, 'Stock Clerk', 43, 750, NULL);

INSERT INTO emp VALUES (
 21, 'Markarian', 'Alexander', 'amarkari',
 '09-OCT-91', NULL, 8, 'Stock Clerk', 43, 850, NULL);

INSERT INTO emp VALUES (
 22, 'Chang', 'Eddie', 'echang',
 '09-OCT-91', NULL, 9, 'Stock Clerk', 44, 800, NULL);

INSERT INTO emp VALUES (
 23, 'Patel', 'Radha', 'rpatel',
 '09-OCT-91', NULL, 9, 'Stock Clerk', 34, 795, NULL);

INSERT INTO emp VALUES (
 24, 'Dancs', 'Bela', 'bdancs',
 '09-MAY-93', NULL, 10, 'Stock Clerk', 45, 860, NULL);

INSERT INTO emp VALUES (
 25, 'Schwartz', 'Sylvie', 'sschwart',
 '09-MAR-91', NULL, 10, 'Stock Clerk', 45, 1100, NULL);



