/* Alimenta a tabela de Pedido */

INSERT INTO pedido VALUES (
   100, 204, '31-AUG-92', '10-SEP-92',
   11, 601100, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   101, 205, '31-AUG-92', '15-SEP-92',
   14, 8056.6, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   102, 206, '01-SEP-92', '08-SEP-92',
   15, 8335, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   103, 208, '02-SEP-92', '22-SEP-92',
   15, 377, 'CASH', 'Y');
INSERT INTO pedido VALUES (
   104, 208, '03-SEP-92', '23-SEP-92',
   15, 32430, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   105, 209, '04-SEP-92', '18-SEP-92',
   11, 2722.24, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   106, 210, '07-SEP-92', '15-SEP-92',
   12, 15634, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   107, 211, '07-SEP-92', '21-SEP-92',
   15, 142171, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   108, 212, '07-SEP-92', '10-SEP-92',
   13, 149570, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   109, 213, '08-SEP-92', '28-SEP-92',
   11, 1020935, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   110, 214, '09-SEP-92', '21-SEP-92',
   11, 1539.13, 'CASH', 'Y');
INSERT INTO pedido VALUES (
   111, 204, '09-SEP-92', '21-SEP-92',
   11, 2770, 'CASH', 'Y');
INSERT INTO pedido VALUES (
   97, 201, '28-AUG-92', '17-SEP-92',
   12, 84000, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   98, 202, '31-AUG-92', '10-SEP-92',
   14, 595, 'CASH', 'Y');
INSERT INTO pedido VALUES (
   99, 203, '31-AUG-92', '18-SEP-92',
   14, 7707, 'CREDIT', 'Y');
INSERT INTO pedido VALUES (
   112, 210, '31-AUG-92', '10-SEP-92',
   12, 550, 'CREDIT', 'Y');

