/* Alimenta a Tabela de Produto */

INSERT INTO produto VALUES (
   10011, 'Bunny Boot',
   'Beginner''s ski boot',
   518,1001,
   150, NULL);
INSERT INTO produto VALUES (
   10012, 'Ace Ski Boot',
   'Intermediate ski boot',
   519,1002,
   200, NULL);
INSERT INTO produto VALUES (
   10013, 'Pro Ski Boot',
   'Advanced ski boot',
   520,1003,
   410, NULL);
INSERT INTO produto VALUES (
   10021, 'Bunny Ski Pole',
   'Beginner''s ski pole',
   528,1011,
   16.25, NULL);
INSERT INTO produto VALUES (
   10022, 'Ace Ski Pole',
   'Intermediate ski pole',
   529,1012,
   21.95, NULL);
INSERT INTO produto VALUES (
   10023, 'Pro Ski Pole',
   'Advanced ski pole',
   530,1013,
   40.95, NULL);
INSERT INTO produto VALUES (
   20106, 'Junior Soccer Ball',
   'Junior Soccer Ball',
   613, NULL,
   11, NULL);
INSERT INTO produto VALUES (
   20108, 'World Cup Soccer Ball',
   'World Cup Soccer Ball',
   615, NULL,
   28, NULL);
INSERT INTO produto VALUES (
   20201, 'World Cup Net',
   'World Cup Net',
   708, NULL,
   123, NULL);
INSERT INTO produto VALUES (
   20510, 'Black Hawk Knee Pads',
   'Knee pads, pair',
   1017, NULL,
   9, NULL);
INSERT INTO produto VALUES (
   20512, 'Black Hawk Elbow Pads',
   'Elbow Pads, pair',
   1019, NULL,
   8, NULL);
INSERT INTO produto VALUES (
   30321, 'Grand Prix Bicycle',
   'Road bicycle',
   828, 1291,
   1669, NULL);
INSERT INTO produto VALUES (
   30326, 'Himalaya Bicycle',
   'Mountain bicycle',
   833,1296,
   582, NULL);
INSERT INTO produto VALUES (
   30421, 'Grand Prix Bicycle Tires',
   'Road bicycle tires',
   927, NULL,
   16, NULL);
INSERT INTO produto VALUES (
   30426, 'Himalaya Tires',
   'Mountain bicycle tires',
   933, NULL,
   18.25, NULL);
INSERT INTO produto VALUES (
   30433, 'New Air Pump',
   'Tire pump',
   940, NULL,
   20, NULL);
INSERT INTO produto VALUES (
   32779, 'Slaker Water Bottle',
   'Water bottle',
   1286, NULL,
   7, NULL);
INSERT INTO produto VALUES (
   32861, 'Safe-T Helmet',
   'Bicycle helmet',
   1368, 1829,
   60, NULL);
INSERT INTO produto VALUES (
   40421, 'Alexeyer Pro Lifting Bar',
   'Straight bar',
   928, 1381,
   65, NULL);
INSERT INTO produto VALUES (
   40422, 'Pro Curing Bar',
   'Curling bar',
   929,1382,
   50, NULL);
INSERT INTO produto VALUES (
   41010, 'Prostar 10 Pound Weight',
   'Ten pound weight',
   517, NULL,
   8, NULL);
INSERT INTO produto VALUES (
   41020, 'Prostar 20 Pound Weight',
   'Twenty pound weitght',
   527, NULL,
   12, NULL);
INSERT INTO produto VALUES (
   41050, 'Prostar 50 Pound Weight',
   'Fifty pound weitght',
   557, NULL,
   25, NULL);
INSERT INTO produto VALUES (
   41080, 'Prostar 80 Pound Weight',
   'Eighty pound weitght',
   587, NULL,
   35, NULL);
INSERT INTO produto VALUES (
   41100, 'Prostar 100 Pound Weight',
   'One hundred pound weitght',
   607, NULL,
   45, NULL);
INSERT INTO produto VALUES (
   50169, 'Major League Baseball',
   'Baseball',
   676,1119,
   4.29, NULL);
INSERT INTO produto VALUES (
   50273, 'Chapman Helmet',
   'Batting helmet',
   780,1223,
   22.89, NULL);
INSERT INTO produto VALUES (
   50417, 'Griffey Glove',
   'Outfielder''s glove',
   924, 1367,
   80, NULL);
INSERT INTO produto VALUES (
   50418, 'Alomar Glove',
   'Infielder''s glove',
   925,1368,
   75, NULL);
INSERT INTO produto VALUES (
   50419, 'Steinbach Glove',
   'Catcher''s glove',
   926,1369,
   80, NULL);