

INSERT INTO imagem VALUES (
   1001, 'JTIFF', 'Y', 'bunboot.tif', NULL);
INSERT INTO imagem VALUES (
   1002, 'JTIFF', 'Y', 'aceboot.tif', NULL);
INSERT INTO imagem VALUES (
   1003, 'JTIFF', 'Y', 'proboot.tif', NULL);
INSERT INTO imagem VALUES (
   1011, 'JTIFF', 'Y', 'bunpole.tif', NULL);
INSERT INTO imagem VALUES (
   1012, 'JTIFF', 'Y', 'acepole.tif', NULL);
INSERT INTO imagem VALUES (
   1013, 'JTIFF', 'Y', 'propole.tif', NULL);
INSERT INTO imagem VALUES (
   1291, 'JTIFF', 'Y', 'gpbike.tif', NULL);
INSERT INTO imagem VALUES (
   1296, 'JTIFF', 'Y', 'himbike.tif', NULL);
INSERT INTO imagem VALUES (
   1829, 'JTIFF', 'Y', 'safthelm.tif', NULL);
INSERT INTO imagem VALUES (
   1381, 'JTIFF', 'Y', 'probar.tif', NULL);
INSERT INTO imagem VALUES (
   1382, 'JTIFF', 'Y', 'curlbar.tif', NULL);
INSERT INTO imagem VALUES (
   1119, 'JTIFF', 'Y', 'baseball.tif', NULL);
INSERT INTO imagem VALUES (
   1223, 'JTIFF', 'Y', 'chaphelm.tif', NULL);
INSERT INTO imagem VALUES (
   1367, 'JTIFF', 'Y', 'grglove.tif', NULL);
INSERT INTO imagem VALUES (
   1368, 'JTIFF', 'Y', 'alglove.tif', NULL);
INSERT INTO imagem VALUES (
   1369, 'JTIFF', 'Y', 'stglove.tif', NULL);
INSERT INTO imagem VALUES (
   1480, 'JTIFF', 'Y', 'cabbat.tif', NULL);
INSERT INTO imagem VALUES (
   1482, 'JTIFF', 'Y', 'pucbat.tif', NULL);
INSERT INTO imagem VALUES (
   1486, 'JTIFF', 'Y', 'winbat.tif', NULL);
COMMIT;




